export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export ZDOTDIR=$XDG_CONFIG_HOME/zsh
export ZSH_CACHE_DIR="$XDG_CACHE_HOME/zsh"

# Set HOMEBREW_PREFIX early so all scripts can use it without calling `brew --prefix`
export HOMEBREW_PREFIX="${HOMEBREW_PREFIX:-/opt/homebrew}"
